keycloak:
  realm: timelineUI
  resource: rest-api
  auth-server-url: 'http://localhost:8800/auth/'
  ssl-required: external
  public-client: 'true'
  bearer-only: 'true'
  cors: 'true'
  principal-attribute: preferred_username
  securityConstraints:
    - securityCollections:
        - name: protected resource
          patterns: ['/locationByTimestamp', '/locationByTimestamp/', '/timerange', '/timerange/', '/testlocationservice', '/testlocationservice/']
      authRoles:
        - 'user'
server:
  port: '8000'
spring:
  data:
    mongodb:
      host: localhost
      port: '27017'
      database: location_DB
      authentication-database: admin